### ISSUE TITLE
Create Virtual environment like docker, virtualbox

### ISSUE THREAD

**Issue by HWataru** [chiptiptech/connect#16]
It's easy to try chiptiptech apps if virtual environment include repositories.
In general many Project have dockerfile or vagrantfile as virtual environment to test, build, run their code.

But I'm not familiar with FPGA. Is it important ?

Anyway, I need virtual environment to run this code.
Please let me know your environment @rasshai .

**Comment by rasshai** [comment]
Thanks for bringing up the issue!

> But I'm not familiar with FPGA. Is it important ?
I'm not sure what you mean by FPGA being "important". However, one can run our framework without an FPGA. (and there is no virtual environment for FPGAs at the moment.)

My environment is
- OS: Ubuntu 16.04
- Python: 3.6.3
- PyYAML: 3.12
- NetworkX: 2.0
- pySerial: 3.4

**Comment by HWataru** [comment]
It mean I wonder FPGA Engineer alway use linux system and not need virtual environments as me.

**Comment by HWataru** [comment]
open #19

**Comment by rasshai** [comment]
I merged the PRs for this Issue (17df41c1da045ef09059b95eae3a9373462aecb9 and bdd8423a2938f8c775d14d851614da2dae5bd994) and mentioned the Dockerfile in README.md. I think this will do for now, but let's improve this virtual environment feature continuously.
